import { Poppins } from "next/font/google";
import "./globals.css";
import { WalletContextProvider } from "@/context/wallet";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata = {
  title: "CORE NFT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WalletContextProvider>
        <body className={poppins.className}>
          <Header />
          <ToastContainer position="top-left" autoClose={4000} />
          {children}
          <Footer />
        </body>
      </WalletContextProvider>
    </html>
  );
}
